[package]
name = "ark-ff-optimized"
version = "0.5.0"
edition = "2024"
authors = ["윤병익 <yeun0908@gmail.com>"]
description = "A fork of https://github.com/andrewmilson/optimized-fields to adapt to ark-ff v0.5"
repository = "https://github.com/newsniper-org/optimized-fields"
homepage = "https://github.com/newsniper-org/optimized-fields"
keywords = ["cryptography", "finite-fields"]
categories = ["cryptography"]
readme = "README.md"
license = "MIT"

[dependencies]
ark-ff = { version = "0.5" }
ark-serialize = { version = "0.5" }
ark-std = { version = "0.5" }
zeroize = "1"
num-bigint = { version = "0.4" }

[dev-dependencies]
ark-algebra-test-templates = "0.5"
ark-algebra-bench-templates = "0.5"

[features]
asm = ["ark-ff/asm"]
parallel = ["ark-ff/parallel", "ark-serialize/parallel"]
std = ["ark-ff/std", "ark-serialize/std", "num-bigint/std"]
rayon = ["ark-ff/rayon", "ark-serialize/rayon"]

[[bench]]
name = "fp64"
path = "benches/fp64.rs"
harness = false

[[bench]]
name = "fp31"
path = "benches/fp31.rs"
harness = false
